package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// This file was generated by Copilot (Opus 5.3) from the OpenAPI YAML specification.
// It contains the client code for the Busy Bar API.

// The Client struct represents a client for the Busy Bar API.
const apiTokenHeader = "X-API-Token"

// The NewClient function creates a new Client with the specified base URL.
type Client struct {
	BaseURL    string
	APIKey     string
	HTTPClient *http.Client
}

// NewClient creates a new Client with the specified base URL.
// This works over USB
func NewClient(baseURL string) *Client {
	return &Client{
		BaseURL:    strings.TrimRight(baseURL, "/"),
		HTTPClient: http.DefaultClient,
	}
}

// NewClientWithAPIKey creates a new Client with the specified base URL and API key.
// This works over Wi-Fi. The API key is your Bar's password, set via the web interface.
func NewClientWithAPIKey(baseURL, apiKey string) *Client {
	client := NewClient(baseURL)
	client.APIKey = apiKey
	return client
}

// do is a helper function that performs an HTTP request to the Busy Bar API.
func (c *Client) do(ctx context.Context, method, path string, query url.Values, payload any) ([]byte, error) {
	client := c.HTTPClient
	if client == nil {
		client = http.DefaultClient
	}

	var body io.Reader
	if payload != nil {
		encodedPayload, err := json.Marshal(payload)
		if err != nil {
			return nil, err
		}
		body = bytes.NewReader(encodedPayload)
	}

	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, body)
	if err != nil {
		return nil, err
	}
	if query != nil {
		req.URL.RawQuery = query.Encode()
	}

	req.Header.Set("accept", "application/json")
	if payload != nil {
		req.Header.Set("content-type", "application/json")
	}
	if c.APIKey != "" {
		req.Header.Set(apiTokenHeader, c.APIKey)
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	responseBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}

	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		var apiErr ErrorResponse
		if len(responseBody) > 0 {
			if err := json.Unmarshal(responseBody, &apiErr); err == nil && apiErr.Error != "" {
				return nil, &APIError{StatusCode: resp.StatusCode, Response: apiErr, Body: responseBody}
			}
		}

		return nil, fmt.Errorf("%s %s returned status %d: %s", method, req.URL.String(), resp.StatusCode, string(responseBody))
	}

	return responseBody, nil
}

// doJSON is a helper function that performs an HTTP request to the Busy Bar API and decodes the JSON response into the specified type.
func doJSON[T any](c *Client, ctx context.Context, method, path string, query url.Values, payload any) (*T, error) {
	resp, err := c.do(ctx, method, path, query, payload)
	if err != nil {
		return nil, err
	}

	var value T
	if len(resp) == 0 {
		return &value, nil
	}

	if err := json.Unmarshal(resp, &value); err != nil {
		return nil, err
	}

	return &value, nil
}
